# action.yml
name: 'apta logdiff'
description: 'Calcuate differences in log files from software executions'
inputs:
  tracefile:
    description: 'current execution traces'
    required: true
    default: 'inputfile.csv'
  inifile:
    description: 'current execution traces'
    required: true
    default: 'inputfile.csv'
outputs:
  resultfile:
    description: 'overview of differences found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tracefile }}
    - --ini=/home/flexfringe/ini/${{ inputs.inifile }}
