# action.yml
name: 'apta logdiff'
description: 'Calcuate differences in log files from software executions'
branding:
  icon: 'file-text'  
  color: 'green'
inputs:
  tracefile:
    description: 'current execution traces'
    required: true
    default: 'inputfile.csv'
  inifile:
    description: 'config file'
    required: true
    default: 'edsm.ini'
  apitoken:
    description: 'The api token to use'
    required: true
  gitref:
    description: 'The git ref to store for this run'
    required: true
    default: ${{ github.ref }}
  reponame:
    description: 'The name of the repository we are running logdiff for'
    required: true
    default: ${{ github.repository }}
  separator:
    description: 'The separator used to parse the input csv file'
    required: true
    default: ','
outputs:
  resultfile:
    description: 'overview of differences found'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apitoken }}
    - ${{ inputs.gitref }}
    - ${{ inputs.reponame }}
    - ${{ inputs.separator }}
    - ${{ inputs.tracefile }}
    - --ini=/home/flexfringe/ini/${{ inputs.inifile }}
